linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 100
    statements: 50
  gocognit:
    # Minimal code complexity to report.
    min-complexity: 10
  goconst:
    # Minimal length of string constant.
    min-len: 3
    # Minimal occurrences count to trigger.
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - whyNoLint
      - paramTypeCombine
    settings: # settings passed to gocritic
      hugeParam:
        sizeThreshold: 90
  gocyclo:
    min-complexity: 15
  gofmt:
    # Simplify code.
    simplify: true
  golint:
    min-confidence: 0.8
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  govet:
    # Report about shadowed variables.
    check-shadowing: true
    enable:
      - atomicalign
  lll:
    line-length: 120
  maligned:
    # Print struct with more effective memory layout.
    suggest-new: true
  misspell:
    locale: US
  nakedret:
    # Make an issue if func has more lines of code than this setting and it has naked returns.
    max-func-lines: 50
  prealloc:
    # Report preallocation suggestions only on simple loops that
    # have no returns/breaks/continues/gotos in them.
    simple: true
    range-loops: true # Report preallocation suggestions on range loops.
    for-loops: true # Report preallocation suggestions on for loops.
  whitespace:
    multi-if: false   # Enforces newlines (or comments) after every multi-line if statement.
    multi-func: false # Enforces newlines (or comments) after every multi-line function signature.

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - gochecknoglobals
    - goconst
    - gocognit
    - gocritic
    - gocyclo
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - gofumpt
    - gofmt
    - godot
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - rowserrcheck
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - sqlclosecheck
    - typecheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gochecknoglobals
        - gosec
        - gomnd
        - scopelint
        - funlen
    - linters:
        - gochecknoglobals
      source: "(chan|cli.Command)"
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
    - path: main\.go
      linters:
        - gochecknoinits
    # Exclude formatting for generated files.
    - path: \*.pb.go
      linters:
        - gofumpt
        - gofmt
    # Exclude some linters from running on swag documentation.
    - linters:
        - godot
        - lll
      source: "^// @"
