version: '3.8'

services:
  nats-streaming:
    image: nats-streaming:alpine
    container_name: tweethub-nats-streaming
    restart: unless-stopped
    ports:
      - 4222:4222
      - 8222:8222
    environment:
      NATS_CLUSTER_ID: "nats-local"

  mongo:
    image: mongo:latest
    container_name: tweethub-mongo
    restart: unless-stopped
    networks:
      - tweethub
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: devpass
      MONGO_INITDB_DATABASE: tweethub
    volumes:
      - ./hack/mongodb/init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: tweethub-redis
    ports:
      - 6379:6379

  tweethub.io:
    image: nginx:alpine
    container_name: tweethub-nginx
    restart: unless-stopped
    networks:
      - tweethub
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  tweets:
    build:
      context: .
      dockerfile: cmd/tweets/Dockerfile
    restart: unless-stopped
    networks:
      - tweethub
    depends_on:
      - mongo
      - nats-streaming
      - redis
      - tweethub.io

  statistics:
    build:
      context: .
      dockerfile: cmd/statistics/Dockerfile
    restart: unless-stopped
    networks:
      - tweethub
    depends_on:
      - mongo
      - nats-streaming
      - redis
      - tweethub.io

networks:
  tweethub: